### PR TITLE
Fix cursor timeout bug

### LINKED ISSUE #39: CursorNotFound exception when processing large stakeholder
# 🐛 Bug Report

During the weekly report generation process, we are getting the following error when processing one of our larger stakeholders (HHS):

```
/var/cyhy/orchestrator# docker-compose logs trustymail_report | less

trustymail_report_1  Generating Trustymail Report...
trustymail_report_1  Traceback (most recent call last):
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 1329, in <module>
trustymail_report_1      main()
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 1319, in main
trustymail_report_1      generator = ReportGenerator(db, args['"AGENCY"'], debug=args['--debug'])
trustymail_report_1    File "/home/reporter/report/generate_trustymail_report.py", line 218, in __init__
trustymail_report_1      for domain_doc in all_domains_cursor:
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1156, in next
trustymail_report_1      if len(self.__data) or self._refresh():
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1093, in _refresh
trustymail_report_1      self.__send_message(g)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 955, in __send_message
trustymail_report_1      address=self.__address)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1346, in _run_operation_with_response
trustymail_report_1      exhaust=exhaust)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1464, in _retryable_read
trustymail_report_1      return func(session, server, sock_info, slave_ok)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1340, in _cmd
trustymail_report_1      unpack_res)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/server.py", line 136, in run_operation_with_response
trustymail_report_1      _check_command_response(first)
trustymail_report_1    File "/usr/local/lib/python3.6/site-packages/pymongo/helpers.py", line 156, in _check_command_response
trustymail_report_1      raise CursorNotFound(errmsg, code, response)
trustymail_report_1  pymongo.errors.CursorNotFound: cursor id 228032354899 not found
```

## To Reproduce

I was unable to reproduce this error by generating the individual report manually.  I suspect it can only be triggered by generating all of the reports (`create_all_reports.py`).

## Expected behavior

The report should generate without any errors.

## Potential solutions

Since the MongoDB cursor timeout is occurring [here](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L218) (as seen in the traceback above), we need to look at where `all_domains_cursor` is created [here](https://github.com/cisagov/trustymail_reporter/blob/develop/report/generate_trustymail_report.py#L155-L159).  Two potential solutions are:
- Try using the `batch_size` parameter to work through the cursor results in smaller batches.
- Set `no_cursor_timeout` to `True` and manually close the cursor (`all_domains_cursor.close()`) when processing is finished.

See [the docs](https://api.mongodb.com/python/current/api/pymongo/collection.html) for details.

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request fixes a bug that was caused HHS Trustworthy Email reports to fail to generate the past couple of weeks.  This pull request resolves issue #39.

## 💭 Motivation and Context

When the report fails to generate we have to go back and regenerate it manually.  [Manual bad, automated good!](https://en.wikipedia.org/wiki/Animal_Farm#Animalism)  

## 🧪 Testing

The pre-commit hooks all pass.  I performed a full test run and verified that this change fixes the problem without unintended side effects.

## 🚥 Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Simple is good!  I'm fully on board with this fix, as long as the full test run is successful.  🧪 👍  
Thanks for taking care of this! 🥇

**Review by mcdonnnj — APPROVED** [review]
Seems like a straightforward fix. 👍

**Comment by jsf9k** [comment]
Well the error still occurs with the simple change.  I think the inside of that loop right where it fails must be taking more than ten minutes in some cases.  It's certainly possible, since the loop contains a database query and then another loop over the results of that query.

I'll try the `no_cursor_timeout` method now, as described in issue #39.

**Comment by jsf9k** [comment]
The `no_cursor_timeout` test was a success.  I ran both the pshtt and trustymail reporting at the same time (as happens when the reporting runs normally) and there were no errors.  In particular, the HHS report generated successfully.  I think these changes are good to go.

**Review by dav3r — APPROVED** [review]
Works for me! 🎯

**Review by mcdonnnj — APPROVED** [review]
Makes sense ✅

**Pull request merged**
