### PR TITLE
Fix LGTM and flake8 warnings

### PR DESCRIPTION
**Pull request by jsf9k**

### CODE REVIEW

**Comment by jsf9k** [comment]
This pull request **fixes 3 alerts** when merging 7e768580b679a44d65a7ca96a6c33382f641170d into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-6c31ea94a75074d1a2772f1fbc410135e6f8d257)

**fixed alerts:**

* 2 for Unused local variable
* 1 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 15 alerts** when merging cd7f32fbc861d2b5106a65a7290fb390fe98912f into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-b8155cb34f0766c4f276eaab867a96795b5b377c)

**fixed alerts:**

* 12 for Unused local variable
* 2 for Unused import
* 1 for Duplicate key in dict literal

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 16 alerts** when merging e72354c18e2c2e046792f92c55cfc309765a655e into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-04483d318761913b4696f8203a6c4aca828d5588)

**fixed alerts:**

* 13 for Unused local variable
* 2 for Unused import
* 1 for Duplicate key in dict literal

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 16 alerts** when merging 0650f96273e65d423a25497033eac2a770ba4f5f into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-7c2e3fdd9cad81295f8682524af4674f1af11e81)

**fixed alerts:**

* 13 for Unused local variable
* 2 for Unused import
* 1 for Duplicate key in dict literal

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 16 alerts** when merging add7468ce77fcaa48d78a859b29d631865002d99 into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-e8226decdb473f33e8c20180599aa66161957250)

**fixed alerts:**

* 13 for Unused local variable
* 2 for Unused import
* 1 for Duplicate key in dict literal

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
This pull request **fixes 16 alerts** when merging 12ded7475fbb08c040bbb97f3bf85b9ddb89a93a into 6011a755b5474e7fb8f0929572075644402674bd - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-f34a06eb87be0d01f5dee30baaae04fd26bb2641)

**fixed alerts:**

* 13 for Unused local variable
* 2 for Unused import
* 1 for Duplicate key in dict literal

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
I generated reports in my `jsf9k` staging environment using this new code and the data from this weekend's BOD 18-01 scanning, verifying that this new code produces the same output as what is currently in `develop`.

**Review by felddy — APPROVED** [review]
Hello darkness my old friend: `LATEX_ESCAPE_MAP`

LGTM

**Pull request merged**
