### PR TITLE
Update base Docker image

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description ##

This pull request bumps the Docker base image to the latest version.

## 💭 Motivation and context ##

With the previous version of the Docker base image the APB builds were failing, and with the latest version they are not.

## 🧪 Testing ##

All automated testing passes.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [x] Finalize version.

## ✅ Post-merge checklist ##

- [x] Add a tag.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
I have no issues with this pull request. Regarding the failed workflows they are due to a missing dependency when trying to build the [`pillow`](https://github.com/python-pillow/Pillow) package per the [Action log](https://github.com/cisagov/trustymail_reporter/runs/7629321685?check_suite_focus=true#step:9:4457). Are we sure we won't end up with the same kind of failure in the future?

**Review by dav3r — APPROVED** [review]
👍 👍

**Comment by jsf9k** [comment]
> I have no issues with this pull request. Regarding the failed workflows they are due to a missing dependency when trying to build the [`pillow`](https://github.com/python-pillow/Pillow) package per the [Action log](https://github.com/cisagov/trustymail_reporter/runs/7629321685?check_suite_focus=true#step:9:4457). Are we sure we won't end up with the same kind of failure in the future?

Those errors were because the build process couldn't find the headers for `zlib`, even though the package `zlib1g-dev` is installed in the Dockerfile.  I don't know why that was happening but it went away after I updated the version of the base Docker image.  I suspect there was a temporary error in the `zlib1g-dev` package upstream, and it got rebuilt by the time I started working on this branch.

Incidentally, this is precisely why the name of this branch does not agree with the contents of the PR; I assumed that I was missing the correct package for the `zlib` headers, so I:
1. Started a new branch to investigate
2. Went ahead and updated the base Docker image to the latest since I was here anyway
3. Expected the build to fail but was surprised that it succeeded

@mcdonnnj, please let me know if this explanation satisfi[c]es you.

**Comment by mcdonnnj** [comment]
> > I have no issues with this pull request. Regarding the failed workflows they are due to a missing dependency when trying to build the [`pillow`](https://github.com/python-pillow/Pillow) package per the [Action log](https://github.com/cisagov/trustymail_reporter/runs/7629321685?check_suite_focus=true#step:9:4457). Are we sure we won't end up with the same kind of failure in the future?
> 
> Those errors were because the build process couldn't find the headers for `zlib`, even though the package `zlib1g-dev` is installed in the Dockerfile. I don't know why that was happening but it went away after I updated the version of the base Docker image. I suspect there was a temporary error in the `zlib1g-dev` package upstream, and it got rebuilt by the time I started working on this branch.
> 
> Incidentally, this is precisely why the name of this branch does not agree with the contents of the PR; I assumed that I was missing the correct package for the `zlib` headers, so I:
> 
>     1. Started a new branch to investigate
> 
>     2. Went ahead and updated the base Docker image to the latest since I was here anyway
> 
>     3. Expected the build to fail but was surprised that it succeeded
> 
> 
> @mcdonnnj, please let me know if this explanation satisfi[c]es you.

@jsf9k That works for me. Thanks for the explanation.

**Pull request merged**
