### PR TITLE
Fix basemap error

### PR DESCRIPTION
**Pull request by jsf9k**
The `Dockerfile` for this project is using `basemap` version 1.1.0, which is from May of 2017.  There is no newer official release, and the library is showing its age.  For instance, `basemap/__init__.py` references `pyproj.pyproj_datadir`, which causes an `AttributeError` to be raised because there is no such attribute.  The simplest solution is just to remove the unused `MyMap` class in `graphs.py`, which is the only place where the `basemap` library is used, and then remove the `basemap` installation from the project's `Dockerfile`.

I also updated the `yaml.load()` call in `generate_trustymail_report.py`.  The loader must now be explicitly specified when calling `yaml.load()` in order to avoid a warning message.  See [here](https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation) for more details.

See also cisagov/pshtt_reporter#29.

### CODE REVIEW

**Comment by jsf9k** [comment]
This pull request **fixes 8 alerts** when merging e9353eb1741ab13cfca54234a26b4a3db44ef0bd into c05b6e2b5639e4d52cc263e90bb252aa11679b80 - [view on LGTM.com](https://lgtm.com/projects/g/cisagov/trustymail_reporter/rev/pr-f7319224e44e27c12af683a590f12ee1918b2643)

**fixed alerts:**

* 4 for Testing equality to None
* 4 for Unused import

---

*Comment posted by [LGTM.com](https://lgtm.com)*

**Comment by jsf9k** [comment]
FWIW, this code was used to generate this weekend's Trustworthy Email reports.

**Review by dav3r — APPROVED** [review]
👍 
We also have some similar code in pshtt_reporter that should be similarly updated:
- https://github.com/cisagov/pshtt_reporter/blob/develop/Dockerfile#L69
- https://github.com/cisagov/pshtt_reporter/blob/develop/report/generate_https_scan_report.py#L775
- https://github.com/cisagov/pshtt_reporter/blob/develop/report/graphs.py#L1-L17
- https://github.com/cisagov/pshtt_reporter/blob/develop/report/graphs.py#L486-L533

**Comment by jsf9k** [comment]
@dav3r, see cisagov/pshtt_reporter#29.

**Pull request merged**
