### PR TITLE
Fix incorrect logic

### PR DESCRIPTION
**Pull request by jsf9k**
The logic that determines whether or not a DMARC report represents an actual failure was incorrect.  It was counting the report as a failure if _either_ DKIM _or_ SPF failed or failed alignment.  The correct behavior is to count the report as a failure if _both_ DKIM _and_ SPF fail or fail alignment.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Makes sense to me- good fix. 👍

**Review by KyleEvers — APPROVED** [review]
Verified on paper it will only return true if both dkim and spf values are false. Looks good. 👍

**Review by felddy — APPROVED** [review]
👌

**Review by mcdonnnj — APPROVED** [review]
Nice catch ✅

**Pull request merged**
